/*
 * job_offer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"
	// "github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{service: s}
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{
		{
			"GetJobOffer",
			strings.ToUpper("Get"),
			"/job_offer",
			c.GetJobOffer,
		},
		{
			"GetOccupation",
			strings.ToUpper("Get"),
			"/occupation",
			c.GetOccupation,
		},
		{
			"GetTotalPopulation",
			strings.ToUpper("Get"),
			"/total_population",
			c.GetTotalPopulation,
		},
		{
			"PostJobOffer",
			strings.ToUpper("Post"),
			"/job_offer",
			c.PostJobOffer,
		},
		{
			"PostOccupation",
			strings.ToUpper("Post"),
			"/occupation",
			c.PostOccupation,
		},
		{
			"PostTotalPopulation",
			strings.ToUpper("Post"),
			"/total_population",
			c.PostTotalPopulation,
		},
	}
}

// GetJobOffer - job_offer
func (c *DefaultApiController) GetJobOffer(w http.ResponseWriter, r *http.Request) {
	// クエリパラメータを取り出す
	params := r.URL.Query()
	// パラメータをjobOfferにセットする
	rs := Nest2Joboffer{PrefCode: params.Get("prefCode"), PrefName: params.Get(("prefName"))}
	// リクエスト用のオブジェクトにパラメータをセットする
	inlineObject := &InlineObject{Result: rs}

	result, err := c.service.GetJobOffer(*inlineObject)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetOccupation - occupation
func (c *DefaultApiController) GetOccupation(w http.ResponseWriter, r *http.Request) {
	inlineObject1 := &InlineObject1{}
	if err := json.NewDecoder(r.Body).Decode(&inlineObject1); err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.GetOccupation(*inlineObject1)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// GetTotalPopulation - total_population
func (c *DefaultApiController) GetTotalPopulation(w http.ResponseWriter, r *http.Request) {
	inlineObject2 := &InlineObject2{}
	if err := json.NewDecoder(r.Body).Decode(&inlineObject2); err != nil {
		w.WriteHeader(500)
		return
	}

	result, err := c.service.GetTotalPopulation(*inlineObject2)
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// PostJobOffer - result
func (c *DefaultApiController) PostJobOffer(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.PostJobOffer()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// PostOccupation - result
func (c *DefaultApiController) PostOccupation(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.PostOccupation()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}

// PostTotalPopulation - result
func (c *DefaultApiController) PostTotalPopulation(w http.ResponseWriter, r *http.Request) {
	result, err := c.service.PostTotalPopulation()
	if err != nil {
		w.WriteHeader(500)
		return
	}

	EncodeJSONResponse(result, nil, w)
}
