/*
 * job_offer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"net/http"
	"strings"

	//"github.com/gorilla/mux"
)

// A DefaultApiController binds http requests to an api service and writes the service results to the http response
type DefaultApiController struct {
	service DefaultApiServicer
}

// NewDefaultApiController creates a default api controller
func NewDefaultApiController(s DefaultApiServicer) Router {
	return &DefaultApiController{ service: s }
}

// Routes returns all of the api route for the DefaultApiController
func (c *DefaultApiController) Routes() Routes {
	return Routes{ 
		{
			"GetJobOffer",
			strings.ToUpper("Get"),
			"/job_offer",
			c.GetJobOffer,
		},
		{
			"GetOccupation",
			strings.ToUpper("Get"),
			"/occupation",
			c.GetOccupation,
		},
		{
			"GetTotalPopulation",
			strings.ToUpper("Get"),
			"/total_population",
			c.GetTotalPopulation,
		},
	}
}

// GetJobOffer - job_offer
func (c *DefaultApiController) GetJobOffer(w http.ResponseWriter, r *http.Request) { 
	inlineObject := &InlineObject{}
	if err := json.NewDecoder(r.Body).Decode(&inlineObject); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.GetJobOffer(*inlineObject)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// GetOccupation - occupation
func (c *DefaultApiController) GetOccupation(w http.ResponseWriter, r *http.Request) { 
	inlineObject1 := &InlineObject1{}
	if err := json.NewDecoder(r.Body).Decode(&inlineObject1); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.GetOccupation(*inlineObject1)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}

// GetTotalPopulation - total_population
func (c *DefaultApiController) GetTotalPopulation(w http.ResponseWriter, r *http.Request) { 
	inlineObject2 := &InlineObject2{}
	if err := json.NewDecoder(r.Body).Decode(&inlineObject2); err != nil {
		w.WriteHeader(500)
		return
	}
	
	result, err := c.service.GetTotalPopulation(*inlineObject2)
	if err != nil {
		w.WriteHeader(500)
		return
	}
	
	EncodeJSONResponse(result, nil, w)
}
