/*
 * job_offer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject1 struct {

	// メッセージ
	Message string `json:"message,omitempty"`

	Result OccupationMiddleCategory `json:"result,omitempty"`
}
