/*
 * job_offer
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Nest1TotalPopulation struct {

	// ラベル + 総人口・転入数・転出数・出生数・死亡数
	Label string `json:"label,omitempty"`

	Data ResultTotalPopulation `json:"data,omitempty"`
}
