openapi: 3.0.0
info:
  title: job_offer
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /job_offer:
    get:
      operationId: get-job_offer
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            examples: {}
            schema:
              properties:
                message:
                  description: |
                    メッセージ
                  type: string
                result:
                  $ref: '#/components/schemas/result_joboffer'
              type: object
      responses:
        "200":
          description: OK
      summary: job_offer
      tags: []
  /occupation:
    get:
      operationId: get-occupation
      parameters: []
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          application/json:
            examples: {}
            schema:
              properties:
                message:
                  description: メッセージ
                  type: string
                result:
                  $ref: '#/components/schemas/occupation_middle_category'
              type: object
      responses:
        "200":
          description: OK
      summary: occupation
      tags: []
  /total_population:
    get:
      operationId: get-total_population
      requestBody:
        $ref: '#/components/requestBodies/inline_object_2'
        content:
          application/json:
            examples: {}
            schema:
              properties:
                message:
                  description: メッセージ
                  type: string
                'result ':
                  $ref: '#/components/schemas/result__total_population'
              type: object
      responses:
        "200":
          description: OK
      summary: total_population
      tags: []
components:
  requestBodies:
    inline_object_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_1'
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
    inline_object_2:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_2'
  schemas:
    result_joboffer:
      properties:
        broadName:
          description: 職業大分類1
          type: string
        valid_job_offer_number:
          description: 有効求人数
          type: number
        valid_jobfinder:
          description: 有効就職者
          type: number
        finding_employment_count:
          description: 就職件数
          type: number
    inline_object:
      properties:
        message:
          description: |
            メッセージ
          type: string
        result:
          $ref: '#/components/schemas/result_joboffer'
      type: object
    occupation_middle_category:
      properties:
        iscoCode:
          description: 職業大分類コード
          type: string
        ismcoCode:
          description: 職業中分類
          type: string
        ismcoName:
          description: 職業中分類名
          type: string
    inline_object_1:
      properties:
        message:
          description: メッセージ
          type: string
        result:
          $ref: '#/components/schemas/occupation_middle_category'
      type: object
    result__total_population:
      properties:
        total_population:
          description: 総人口
          type: number
        bitrh_number:
          description: 出生数
          type: number
        died_number:
          description: 死亡数
          type: number
    inline_object_2:
      properties:
        message:
          description: メッセージ
          type: string
        'result ':
          $ref: '#/components/schemas/result__total_population'
      type: object
